apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ $.Values.name }}-tls-creator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ $.Values.name }}-tls-creator
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name:  {{ $.Values.name }}-tls-creator
      labels:
        app: {{ $.Values.name }}-tls-creator
    spec:
      containers:
      - name: create
        image: jettech/kube-webhook-certgen:v1.2.1
        imagePullPolicy: IfNotPresent
        args:
        - create
        - --host={{ $.Values.name }},{{ $.Values.name }}.{{ .Release.Namespace }}.svc
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ $.Values.name }}
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: OnFailure
      serviceAccountName: {{ $.Values.name }}
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
