apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
webhooks:
- name: {{ $.Values.name }}.{{ .Release.Namespace }}.svc
  clientConfig:
    service:
      name: {{ $.Values.name }}
      namespace : {{ .Release.Namespace }}
      path: "/mutate"
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
