
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.name }}
    namespace : {{ .Release.Namespace }}